spring:
    application:
        name: myportfolio
    data:
        mongodb:
            uri: mongodb+srv://abhijithlalharivaram:<Abhijithabhi%402001>@portfolio.ldwmk.mongodb.net/?retryWrites=true&w=majority&appName=portfolio
            database: projects

